name: SuperMarioUhc
author: Playmore
version: 0.0.3
main: fr.playmore.supermario.Plugin
commands:
  start:
    description: lance la partie
    use: operator.use
  state:
    description: permet de connaitre l'etat de la partie
    use: operator.use
  add:
    description: permet d'ajouter des roles dans la role liste
    use: operator.use
  remove:
    description: permet de retirer des roles dans la role liste
    use: operator.use
  mu:
    description: commande pour s'ajouter dans la liste des participant en choisissant son role
    use: