name: SuperMarioUhc
author: Playmore
version: 0.0.3
main: fr.playmore.supermario.Plugin
commands:
  start:
    description: lance la partie
    use: operator.use
  state:
    description: permet de connaitre l'etat de la partie
    use: operator.use